<?php

use kartik\grid\GridView;

// $isFa below determines if export['fontAwesome'] property is set to true.
$heading = true;
$isFa = true;
$pdfHeader = '';
$pdfFooter = '';
$title = 'PKS System';

$defaultExportConfig = [
    GridView::HTML => [
        'label' => Yii::t('kvgrid', 'HTML'),
        'icon' => $isFa ? 'file-text' : 'floppy-saved',
        'iconOptions' => ['class' => 'text-info'],
        'showHeader' => true,
        'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => Yii::t('kvgrid', 'grid-export'),
        'alertMsg' => Yii::t('kvgrid', 'The HTML export file will be generated for download.'),
        'options' => ['title' => Yii::t('kvgrid', 'Hyper Text Markup Language')],
        'mime' => 'text/html',
        'config' => [
            'cssFile' => 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'
        ]
    ],
    GridView::CSV => [
        'label' => Yii::t('kvgrid', 'CSV'),
        'icon' => $isFa ? 'file-code-o' : 'floppy-open', 
        'iconOptions' => ['class' => 'text-primary'],
        'showHeader' => true,
        'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => Yii::t('kvgrid', 'grid-export'),
        'alertMsg' => Yii::t('kvgrid', 'The CSV export file will be generated for download.'),
        'options' => ['title' => Yii::t('kvgrid', 'Comma Separated Values')],
        'mime' => 'application/csv',
        'config' => [
            'colDelimiter' => ",",
            'rowDelimiter' => "\r\n",
        ]
    ],
    GridView::TEXT => [
        'label' => Yii::t('kvgrid', 'Text'),
        'icon' => $isFa ? 'file-text-o' : 'floppy-save',
        'iconOptions' => ['class' => 'text-muted'],
        'showHeader' => true,
        'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => Yii::t('kvgrid', 'grid-export'),
        'alertMsg' => Yii::t('kvgrid', 'The TEXT export file will be generated for download.'),
        'options' => ['title' => Yii::t('kvgrid', 'Tab Delimited Text')],
        'mime' => 'text/plain',
        'config' => [
            'colDelimiter' => "\t",
            'rowDelimiter' => "\r\n",
        ]
    ],
    GridView::EXCEL => [
        'label' => Yii::t('kvgrid', 'Excel'),
        'icon' => $isFa ? 'file-excel-o' : 'floppy-remove',
        'iconOptions' => ['class' => 'text-success'],
        'showHeader' => true,
        'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => Yii::t('kvgrid', 'grid-export'),
        'alertMsg' => Yii::t('kvgrid', 'The EXCEL export file will be generated for download.'),
        'options' => ['title' => Yii::t('kvgrid', 'Microsoft Excel 95+')],
        'mime' => 'application/vnd.ms-excel',
        'config' => [
            'worksheet' => Yii::t('kvgrid', 'ExportWorksheet'),
            'cssFile' => ''
        ]
    ],
   GridView::PDF => [
       'label' => Yii::t('kvgrid', 'PDF'),
       'icon' => $isFa ? 'file-pdf-o' : 'floppy-disk',
       'iconOptions' => ['class' => 'text-danger'],
       'showHeader' => true,
       'showPageSummary' => true,
       'showFooter' => true,
       'showCaption' => true,
       'filename' => Yii::t('kvgrid', 'grid-export'),
       'alertMsg' => Yii::t('kvgrid', 'The PDF export file will be generated for download.'),
       'options' => ['title' => Yii::t('kvgrid', 'Portable Document Format')],
       'mime' => 'application/pdf',
       'config' => [
           'mode' => 'c',
           'format' => 'A4-L',
           'destination' => 'D',
           'marginTop' => 20,
           'marginBottom' => 20,
           'cssInline' => '.kv-wrap{padding:20px;}' .
               '.kv-align-center{text-align:center;}' .
               '.kv-align-left{text-align:left;}' .
               '.kv-align-right{text-align:right;}' .
               '.kv-align-top{vertical-align:top!important;}' .
               '.kv-align-bottom{vertical-align:bottom!important;}' .
               '.kv-align-middle{vertical-align:middle!important;}' .
               '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
               '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
               '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
           'methods' => [
               'SetHeader' => [
                   ['odd' => $pdfHeader, 'even' => $pdfHeader]
               ],
               'SetFooter' => [
                   ['odd' => $pdfFooter, 'even' => $pdfFooter]
               ],
           ],
           'options' => [
               'title' => $title,
               'subject' => Yii::t('kvgrid', 'PDF export generated by kartik-v/yii2-grid extension'),
               'keywords' => Yii::t('kvgrid', 'krajee, grid, export, yii2-grid, pdf')
           ],
           'contentBefore'=>'',
           'contentAfter'=>''
       ]
   ],
    GridView::JSON => [
        'label' => Yii::t('kvgrid', 'JSON'),
        'icon' => $isFa ? 'file-code-o' : 'floppy-open',
        'iconOptions' => ['class' => 'text-warning'],
        'showHeader' => true,
        'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => Yii::t('kvgrid', 'grid-export'),
        'alertMsg' => Yii::t('kvgrid', 'The JSON export file will be generated for download.'),
        'options' => ['title' => Yii::t('kvgrid', 'JavaScript Object Notation')],
        'mime' => 'application/json',
        'config' => [
            'colHeads' => [],
            'slugColHeads' => false,
            'jsonReplacer' => null,
            'indentSpace' => 4
        ]
    ],
];